Feature/project creation
TitusCln/ScrumBoardSystem-back pull request #19
Opened 2020-08-17 18:59 UTC by TitusCln

2020-08-20 14:56 UTC, oscarSantoyo commented
@TitusCln Is this PR ready to review?

2020-08-22 13:50 UTC, oscarSantoyo commented on contracts/src/main/java/com/sbs/contracts/clients/UserStoryProxy.java
> +import org.springframework.web.bind.annotation.*;
Please deactivate the folding imports in your IDE https://stackoverflow.com/questions/3348816/intellij-never-use-wildcard-imports

- [x] Use single imports

2020-08-22 13:52 UTC, oscarSantoyo commented on contracts/src/main/java/com/sbs/contracts/clients/UserStoryProxy.java
> +  public Iterable<UserStoryDTO> getProjectUserStories(@RequestParam(value = "ids") Long[] ids);
I think a better name for this method is `getUserStoriesByIds`

2020-08-22 13:55 UTC, oscarSantoyo commented on projects/src/main/java/com/sbs/projects/models/ProjectSprint.java
> +import javax.persistence.*;
- [x] Use unfold imports.

2020-08-22 14:00 UTC, oscarSantoyo commented on userStories/src/main/java/com/sbs/userStories/UserStoryController.java
> +  public Iterable<UserStoryDTO> getUsersStoriesByIds(@RequestParam Long[] ids) {
This naming is correct, proxy had a different one.

2020-08-22 14:01 UTC, oscarSantoyo commented on userStories/src/main/java/com/sbs/userStories/services/impl/UserStoryServiceImpl.java
> +    //    private Stream<S> getOptionalSteam(Collection<T> iterable){
Remove commented code.

2020-08-22 14:01 UTC, oscarSantoyo requested changes
Done for now, please address my comments.

2020-08-22 14:08 UTC, TitusCln commented on userStories/src/main/java/com/sbs/userStories/services/impl/UserStoryServiceImpl.java
> +    //    private Stream<S> getOptionalSteam(Collection<T> iterable){
this commented code it was for you to check if it was possible to create de common generic method utility for this code repetitive implementation @oscarSantoyo 

`Optional.ofNullable(updatedUserStory.getLabels())
              .orElse(new HashSet<>())
              .parallelStream()`

2020-08-24 04:59 UTC, oscarSantoyo approved these changes
Good job :medal_military:

2020-08-24 04:59 UTC, merged