ADD: Swagger dependencies and configuration
TitusCln/ScrumBoardSystem-back pull request #32
Opened 2020-09-03 17:01 UTC by TitusCln

closes #31

2020-09-03 20:18 UTC, TitusCln commented
@oscarSantoyo  please i've already implement basic swagger documentation

2020-09-07 14:14 UTC, oscarSantoyo requested changes
Hey @TitusCln I tried out this endpoint and I'm getting XML response
http://localhost:8090/projects/1?withSprints=true

Not sure if all of them have the same issue, could you review it please.

2020-09-07 14:14 UTC, oscarSantoyo commented on projects/src/main/java/com/sbs/projects/ProjectControllerImpl.java
> +    @ApiOperation(value = "Gets the Project with the specified projectId")
As a good practice, all methods from an interface should be marked as Override

2020-09-07 14:16 UTC, oscarSantoyo commented
Good Job, just left a pair of comments.

2020-09-07 17:14 UTC, TitusCln commented
@oscarSantoyo  i've already fix the comments

2020-09-08 03:35 UTC, oscarSantoyo approved these changes
good job!! :1st_place_medal:

2020-09-08 03:35 UTC, merged